name: kekkon
main: syouyu\kekkon\Main
version: 1.0.0
api: [3.0.0,4.0.0]
load: POSTWORLD
author: syouyu

commands:
  kekkon:
    description: 結婚できます
    usage: /kekkon
  rikon:
    description: 離婚できます
    usage: /rikon